feat: add the option to include external (non-Lean) build dependencies
This is nececssary to build packages such as ProofWidgets, which depends
on npm. Otherwise, it yields the following error:

Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/4mq3s6jrz2sjqngyyl98ngkfvgfjwz5j-source
source root is source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
⣾ [0/0] Running job computation ✖ [7/27] Building proofwidgets/widgetJsAll
trace: /build/source/widget> npm clean-install
trace: stderr:
could not execute external process 'npm'
error: external command 'npm' exited with code 255
Some required targets logged failures:
- proofwidgets/widgetJsAll
error: build failed